### ISSUE TITLE
JTS library update required: com.vividsolutions ==> org.locationtech

### ISSUE THREAD

**Issue by SanderH** [gidema/josm-ods-bag#29]
JTS library is updated and package names changed.

Applies to both openservices and ods-bag plugin.

Tried to create a pull request, but didn't get the last errors out.

You may find more information in posts from https://forum.openstreetmap.org/viewtopic.php?pid=764035#p764035

```
2019-09-27 14:02:50.995 SEVERE: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin ods-bag. Cause: java.lang.reflect.InvocationTargetException. Cause: java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/Geometry. Cause: java.lang.ClassNotFoundException: com.vividsolutions.jts.geom.Geometry
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin ods-bag
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:369)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:804)
        at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:890)
        at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:933)
        at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:1148)
        at org.openstreetmap.josm.gui.MainApplication.mainJOSM(MainApplication.java:909)
        at org.openstreetmap.josm.gui.MainApplication$3.processArguments(MainApplication.java:279)
        at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:706)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:364)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/Geometry
        at org.openstreetmap.josm.plugins.ods.bag.BagImportModule.<init>(BagImportModule.java:40)
        at org.openstreetmap.josm.plugins.ods.bag.BagImportPlugin.<init>(BagImportPlugin.java:8)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: com.vividsolutions.jts.geom.Geometry
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.openstreetmap.josm.plugins.PluginClassLoader.loadClass(PluginClassLoader.java:73)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more
```

**Comment by gidema** [comment]
I'm afraid that this might mean de end of this plug-in. The complexity has grown beyond my capabilities. The changes in the JTS library are solvable, but geotools library has changes as well. Getting Josm and all libraries with their own peculiarities to communicate with each other without version conficts is more than I can manage right now.

**Comment by gidema** [comment]
Fixed
